#!/bin/bash -e
#
# ==============================================================================
# PAQUETE: canaima-estilo-visual-iconos-gnome
# ARCHIVO: postrm
# DESCRIPCIÓN: Revierte los cambios hechos por el paquete en los scripts del
#              mantenedor, de forma tal de asegurarse que el sistema quede
#              como estaba antes de su instalación.
# COPYRIGHT:
#  (C) 2010 Sasha Veronica Solano Grosjean <sashasolano@gmail.com>
# LICENCIA: GPL3
# ==============================================================================
#
# Este programa es software libre. Puede redistribuirlo y/o modificarlo bajo los
# términos de la Licencia Pública General de GNU (versión 3).

PKG="canaima-estilo-visual-iconos-gnome"

case ${1} in

        purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		rm -rf /usr/share/icons/canaima-iconos/icon-theme.cache
	;;

        *)

                echo "postrm no reconoce el argumento '"${1}"'" >&2
                exit 1
        ;;

esac

#DEBHELPER#

exit 0
